name = "synpixel/chrome"
version = "2.0.1"
description = "An implementation of the Chrome DevTools Protocol for Lune"
authors = ["synpixel"]
license = "MIT"
repository = "https://github.com/synpixel/chrome.luau"
includes = ["pesde.toml", "README.md", "LICENSE", "src/**/*"]

[engines]
lune = "^0.10.3"

[target]
environment = "lune"
lib = "src/init.luau"

[indices]
default = "https://github.com/daimond113/pesde-index"

[dependencies]
base64 = { name = "synpixel/base64", version = "^3.0.1", target = "luau" }
